apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderator-app
  labels:
    app: moderator-app
  namespace: namespace-workflow-1702549467227
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderator-app
  template:
    metadata:
      labels:
        app: moderator-app
    spec:
      containers:
        - name: moderator-app
          image: acrworkflow1702549467227.azurecr.io/image-workflow-1702549467227:latest
          ports:
            - containerPort: 8080