apiVersion: v1
kind: Service
metadata:
  name: moderator-app
  namespace: namespace-workflow-1702552041339
spec:
  type: LoadBalancer
  selector:
    app: moderator-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080