
package com.vidyo.moderatorapp.wsdl;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "ScheduledRoomCreationFault", targetNamespace = "http://portal.vidyo.com/user/v1_1")
public class ScheduledRoomCreationFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ScheduledRoomCreationFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ScheduledRoomCreationFault_Exception(String message, ScheduledRoomCreationFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public ScheduledRoomCreationFault_Exception(String message, ScheduledRoomCreationFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.vidyo.moderatorapp.wsdl.ScheduledRoomCreationFault
     */
    public ScheduledRoomCreationFault getFaultInfo() {
        return faultInfo;
    }

}
