FROM eclipse-temurin:17
LABEL mentainer="kkhurana10@gmail.com"
WORKDIR /app
COPY build/libs/portalapp-0.0.1-SNAPSHOT.jar /app/portalapp-0.0.1-SNAPSHOT.jar 
ENTRYPOINT ["java", "-jar", "/app/portalapp-0.0.1-SNAPSHOT.jar"]