
package com.vidyo.portalapp.wsdl;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "ControlMeetingFault", targetNamespace = "http://portal.vidyo.com/user/v1_1")
public class ControlMeetingFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ControlMeetingFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ControlMeetingFault_Exception(String message, ControlMeetingFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public ControlMeetingFault_Exception(String message, ControlMeetingFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.vidyo.portalapp.wsdl.ControlMeetingFault
     */
    public ControlMeetingFault getFaultInfo() {
        return faultInfo;
    }

}
