
package com.vidyo.portalapp.wsdl;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "LogAggregationDisabledFault", targetNamespace = "http://portal.vidyo.com/user/v1_1")
public class LogAggregationDisabledFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private LogAggregationDisabledFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public LogAggregationDisabledFault_Exception(String message, LogAggregationDisabledFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public LogAggregationDisabledFault_Exception(String message, LogAggregationDisabledFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.vidyo.portalapp.wsdl.LogAggregationDisabledFault
     */
    public LogAggregationDisabledFault getFaultInfo() {
        return faultInfo;
    }

}
